### ISSUE TITLE
Charts should save a reference to the colour palette instead of the colour itself

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3625]
### Description

Instead of saving colours, we should be saving a reference to the colour palette index.

Eg: I want this series to use the colour in position 5. So then if I changed the org colour palette the series would pick up the new colour in position 5

### What problem does this solve?

The problem with saving the colours is that from that point on the series will use those colours even if the org colour palette changes. This is super annoying because the user would need to go to each chart and change the colours one by one.

**Comment by TuringLovesDeathMetal** [comment]
This issue has been resolved

**Comment by jesshitchcock** [comment]
Reopening this thread — I don't think this was actually resolved. Series colours are still persisted as literal hex strings (`color?: string` on `SeriesMetadata` in `packages/common/src/types/savedCharts.ts`), and `getSeriesColor` in `VisualizationProvider.tsx` returns that hex directly with no palette-index lookup. So changing the org palette still won't propagate to previously-styled series, which is the pain described here.

There *is* now an org/project colour palette system, but it only affects the default palette a chart draws from — individual series colours set by users are still frozen.

Leaving open as a valid feature request.

**Comment by jpetey75** [comment]
A big chunk of this shipped: color palettes can now be referenced at chart, dashboard, space, and project level ([#22769](https://github.com/lightdash/lightdash/pull/22769), [#22794](https://github.com/lightdash/lightdash/pull/22794)), and default series colors resolve from the active palette at render time, so palette edits flow through to charts you haven't customized. Series colors you assign by hand are saved as raw hex rather than a palette position, so those don't follow palette changes yet. Keeping this open for that.
