### ISSUE TITLE
x-axis labels overlaps on small  monthly / weekly charts

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4431]
### Description

![image](https://user-images.githubusercontent.com/1983672/217866608-8de7ce46-3d05-459a-8a04-dd23c22c95aa.png)

on a small chart on a dashboard looks like this :

![image](https://user-images.githubusercontent.com/1983672/217866753-a736f1c7-7d54-4d20-97db-63524d26b74c.png)

**Comment by magnew** [comment]
Not stale, we still see issues with this

**Comment by rephus** [comment]
I don't think this is an issue anymore, I can't replicate. This probably got fixed in a nother ticket. 

For week and month, we avoid overlapping by skipping months if needed (automatically handled by echarts) 
![image](https://github.com/lightdash/lightdash/assets/1983672/0e64bed3-a956-463b-b2ac-465881dbe4ad)

![image](https://github.com/lightdash/lightdash/assets/1983672/ef81f350-93ad-44d3-8e28-b40f8b55da27)

**Comment by TuringLovesDeathMetal** [comment]
This bug is still happening in some parts of the app. I can't find a pattern to reproduce it. 

Here are examples where it breaks:
- [example 1](https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/tables/stripe_subscriptions?create_saved_chart_version=%7B%22uuid%22%3A%22eff191e8-e9e8-4497-b1d0-cfbe5e3ae25a%22%2C%22projectUuid%22%3A%2221eef0b9-5bae-40f3-851e-9554588e71a6%22%2C%22name%22%3A%22KPI%3A+What%27s+our+MRR+vs.+our+target%3F%22%2C%22description%22%3A%22Monthly+recurring+revenue+for+cloud+organizations+vs.+our+target%22%2C%22tableName%22%3A%22stripe_subscriptions%22%2C%22updatedAt%22%3A%222024-11-29T11%3A45%3A51.249Z%22%2C%22updatedByUser%22%3A%7B%22userUuid%22%3A%2239b4685e-840b-48c8-b84b-b0f90b76d923%22%2C%22firstName%22%3A%22Katie%22%2C%22lastName%22%3A%22Hindson%22%7D%2C%22metricQuery%22%3A%7B%22exploreName%22%3A%22stripe_subscriptions%22%2C%22dimensions%22%3A%5B%22stripe_subscriptions_created_at_week%22%5D%2C%22metrics%22%3A%5B%22stripe_subscriptions_total_monthly_plan_unit_amount%22%5D%2C%22filters%22%3A%7B%22dimensions%22%3A%7B%22id%22%3A%226dd1e7ec-ce90-4fe7-8258-f1895b7afdc6%22%2C%22and%22%3A%5B%7B%22id%22%3A%22ad09d2f1-f3e1-439a-b4ac-8513ede58f24%22%2C%22target%22%3A%7B%22fieldId%22%3A%22stripe_subscriptions_status%22%7D%2C%22values%22%3A%5B%22active%22%2C%22past_due%22%5D%2C%22operator%22%3A%22equals%22%2C%22required%22%3Afalse%7D%5D%7D%2C%22metrics%22%3A%7B%22id%22%3A%2212547a9f-4e7b-4f27-99d8-b18f922e2a41%22%2C%22and%22%3A%5B%5D%7D%2C%22tableCalculations%22%3A%7B%22id%22%3A%22309e4ce2-a1d2-4c2e-adbd-14bf685c85f0%22%2C%22and%22%3A%5B%5D%7D%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22stripe_subscriptions_created_at_week%22%2C%22descending%22%3Afalse%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%7B%22name%22%3A%22m_r_r%22%2C%22displayName%22%3A%22MRR%22%2C%22sql%22%3A%22Sum%28%24%7Bstripe_subscriptions.total_monthly_plan_unit_amount%7D%29+OVER%28PARTITION+BY+NULL+ORDER+BY+%24%7Bstripe_subscriptions.created_at_week%7D+ASC%29%22%2C%22format%22%3A%7B%22type%22%3A%22currency%22%2C%22currency%22%3A%22USD%22%2C%22separator%22%3A%22default%22%7D%2C%22type%22%3A%22number%22%7D%5D%2C%22additionalMetrics%22%3A%5B%5D%2C%22customDimensions%22%3A%5B%5D%2C%22metadata%22%3A%7B%22hasADateDimension%22%3A%7B%22name%22%3A%22created_at_week%22%2C%22label%22%3A%22Created+at+week%22%7D%7D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22stripe_subscriptions_created_at_week%22%2C%22yField%22%3A%5B%22stripe_subscriptions_total_monthly_plan_unit_amount%22%2C%22m_r_r%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%7D%7D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22stripe_subscriptions_created_at_week%22%2C%22stripe_subscriptions_total_monthly_plan_unit_amount%22%2C%22m_r_r%22%5D%7D%2C%22organizationUuid%22%3A%22d413dcea-4c8f-46b6-baa5-23885490e08b%22%2C%22spaceUuid%22%3A%2277e62741-9f91-45a4-8b88-069cebb20505%22%2C%22spaceName%22%3A%22%F0%9F%A4%93+Key+Company+Dashboards%22%2C%22pinnedListUuid%22%3Anull%2C%22pinnedListOrder%22%3Anull%2C%22dashboardUuid%22%3Anull%2C%22dashboardName%22%3Anull%2C%22colorPalette%22%3A%5B%22%237262FF%22%2C%22%23D7C1FA%22%2C%22%2398F4D1%22%2C%22%23000000%22%2C%22%23fc8452%22%2C%22%23fac858%22%2C%22%23ff4d56%22%2C%22%233ba272%22%5D%2C%22slug%22%3A%22kpi-what-s-our-mrr-vs-our-target-%22%2C%22isPrivate%22%3Afalse%2C%22access%22%3A%5B%7B%22userUuid%22%3A%2239b4685e-840b-48c8-b84b-b0f90b76d923%22%2C%22firstName%22%3A%22Katie%22%2C%22lastName%22%3A%22Hindson%22%2C%22email%22%3A%22katie%40lightdash.com%22%2C%22role%22%3A%22admin%22%2C%22hasDirectAccess%22%3Atrue%2C%22inheritedRole%22%3A%22admin%22%2C%22inheritedFrom%22%3A%22organization%22%2C%22projectRole%22%3A%22admin%22%7D%5D%7D)
- [example 2](https://analytics.lightdash.cloud/share/afSXv_PXS1OJQzn6MNQtV)

Here are examples where it doesn't break:
- [example 1](https://analytics.lightdash.cloud/projects/8a223608-a1e4-426e-adcd-0598ea72b9f8/tables/dbt_orders?create_saved_chart_version=%7B%22uuid%22%3A%22f093dae3-3589-414c-8b15-ebac67b9fba9%22%2C%22projectUuid%22%3A%228a223608-a1e4-426e-adcd-0598ea72b9f8%22%2C%22name%22%3A%22What%27s+the+average+number+of+weekly+orders+per+user%3F%22%2C%22description%22%3A%22What%27s+the+average+number+of+weekly+orders+per+user%3F%22%2C%22tableName%22%3A%22dbt_orders%22%2C%22updatedAt%22%3A%222024-03-29T14%3A22%3A59.825Z%22%2C%22updatedByUser%22%3A%7B%22userUuid%22%3A%22fa9ee7cc-ebf1-479a-b094-7792f0bb4692%22%2C%22firstName%22%3A%22Marshall%22%2C%22lastName%22%3A%22Agnew%22%7D%2C%22metricQuery%22%3A%7B%22exploreName%22%3A%22dbt_orders%22%2C%22dimensions%22%3A%5B%22dbt_orders_order_date_week%22%5D%2C%22metrics%22%3A%5B%22dbt_orders_count_distinct_user_id%22%2C%22dbt_orders_count_distinct_order_id%22%5D%2C%22filters%22%3A%7B%22dimensions%22%3A%7B%22id%22%3A%2224fd55a5-0f89-42b7-b3d1-eb85678440fe%22%2C%22and%22%3A%5B%5D%7D%2C%22metrics%22%3A%7B%22id%22%3A%227228c6a3-a74f-49d2-91c8-9f4c3e536d21%22%2C%22and%22%3A%5B%5D%7D%2C%22tableCalculations%22%3A%7B%22id%22%3A%2225170cc8-ced1-4764-90a3-f0708268492f%22%2C%22and%22%3A%5B%5D%7D%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_orders_order_date_week%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%7B%22name%22%3A%22average_orders_per_user%22%2C%22displayName%22%3A%22average+orders+per+user%22%2C%22sql%22%3A%22ROUND%28%24%7Bdbt_orders.count_distinct_order_id%7D%2F%24%7Bdbt_orders.count_distinct_user_id%7D%2C+2%29%22%7D%5D%2C%22additionalMetrics%22%3A%5B%5D%2C%22customDimensions%22%3A%5B%5D%2C%22metadata%22%3A%7B%22hasADateDimension%22%3A%7B%22name%22%3A%22order_date_week%22%2C%22label%22%3A%22Order+date+week%22%7D%7D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22dbt_orders_order_date_week%22%2C%22yField%22%3A%5B%22average_orders_per_user%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%22xAxis%22%3A%5B%7B%22name%22%3A%22Date+%28week%29%22%7D%5D%2C%22yAxis%22%3A%5B%7B%22name%22%3A%22Average+num+orders+per+user%22%7D%2C%7B%7D%5D%2C%22series%22%3A%5B%7B%22type%22%3A%22line%22%2C%22color%22%3A%22%237262ff%22%2C%22label%22%3A%7B%22show%22%3Atrue%2C%22position%22%3A%22top%22%7D%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_orders_order_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22average_orders_per_user%22%7D%7D%2C%22yAxisIndex%22%3A0%7D%5D%7D%7D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_orders_order_date_week%22%2C%22dbt_orders_count_distinct_user_id%22%2C%22dbt_orders_count_distinct_order_id%22%2C%22average_orders_per_user%22%5D%7D%2C%22organizationUuid%22%3A%22d413dcea-4c8f-46b6-baa5-23885490e08b%22%2C%22spaceUuid%22%3A%22c6bc2f47-32ba-4141-a8a6-80618abb18cc%22%2C%22spaceName%22%3A%22Shared%22%2C%22pinnedListUuid%22%3Anull%2C%22pinnedListOrder%22%3Anull%2C%22dashboardUuid%22%3Anull%2C%22dashboardName%22%3Anull%2C%22colorPalette%22%3A%5B%22%237262FF%22%2C%22%23D7C1FA%22%2C%22%2398F4D1%22%2C%22%23000000%22%2C%22%23fc8452%22%2C%22%23fac858%22%2C%22%23ff4d56%22%2C%22%233ba272%22%5D%2C%22slug%22%3A%22what-s-the-average-number-of-weekly-orders-per-user-%22%2C%22isPrivate%22%3Afalse%2C%22access%22%3A%5B%7B%22userUuid%22%3A%2239b4685e-840b-48c8-b84b-b0f90b76d923%22%2C%22firstName%22%3A%22Katie%22%2C%22lastName%22%3A%22Hindson%22%2C%22email%22%3A%22katie%40lightdash.com%22%2C%22role%22%3A%22admin%22%2C%22hasDirectAccess%22%3Afalse%2C%22inheritedRole%22%3A%22admin%22%2C%22inheritedFrom%22%3A%22organization%22%2C%22projectRole%22%3A%22admin%22%7D%5D%7D)
- [example 2](https://analytics.lightdash.cloud/projects/8a223608-a1e4-426e-adcd-0598ea72b9f8/tables/dbt_users?create_saved_chart_version=%7B%22uuid%22%3A%22c5dfdb98-b4dd-4091-9529-9c2fd437b083%22%2C%22projectUuid%22%3A%228a223608-a1e4-426e-adcd-0598ea72b9f8%22%2C%22name%22%3A%22How+many+users+were+created+each+week%3F%21%21%21%21%21%22%2C%22description%22%3A%22How+many+users+were+created+each+week%3F%22%2C%22tableName%22%3A%22dbt_users%22%2C%22updatedAt%22%3A%222024-06-03T19%3A47%3A13.744Z%22%2C%22updatedByUser%22%3A%7B%22userUuid%22%3A%22b19fb2a5-edd3-4165-97b8-318db40d4e22%22%2C%22firstName%22%3A%22Hamzah%22%2C%22lastName%22%3A%22Chaudhary%22%7D%2C%22metricQuery%22%3A%7B%22exploreName%22%3A%22dbt_users%22%2C%22dimensions%22%3A%5B%22dbt_users_created_date_week%22%5D%2C%22metrics%22%3A%5B%22dbt_users_count_distinct_of_user_id%22%5D%2C%22filters%22%3A%7B%22dimensions%22%3A%7B%22id%22%3A%221a24dd4d-806d-4467-8ab3-db805bae04d3%22%2C%22and%22%3A%5B%5D%7D%2C%22metrics%22%3A%7B%22id%22%3A%22598251a8-b3f3-4002-a37c-038ade61cfd6%22%2C%22and%22%3A%5B%5D%7D%2C%22tableCalculations%22%3A%7B%22id%22%3A%2228082d75-4dcd-427e-a25a-8142e1cf304e%22%2C%22and%22%3A%5B%5D%7D%7D%2C%22sorts%22%3A%5B%7B%22fieldId%22%3A%22dbt_users_created_date_week%22%2C%22descending%22%3Atrue%7D%5D%2C%22limit%22%3A500%2C%22tableCalculations%22%3A%5B%5D%2C%22additionalMetrics%22%3A%5B%5D%2C%22customDimensions%22%3A%5B%5D%2C%22metadata%22%3A%7B%22hasADateDimension%22%3A%7B%22name%22%3A%22created_date_week%22%2C%22label%22%3A%22Created+date+week%22%7D%7D%7D%2C%22chartConfig%22%3A%7B%22type%22%3A%22cartesian%22%2C%22config%22%3A%7B%22layout%22%3A%7B%22xField%22%3A%22dbt_users_created_date_week%22%2C%22yField%22%3A%5B%22dbt_users_count_distinct_of_user_id%22%5D%2C%22flipAxes%22%3Afalse%7D%2C%22eChartsConfig%22%3A%7B%22xAxis%22%3A%5B%7B%22name%22%3A%22Date+%28week%29%22%7D%5D%2C%22yAxis%22%3A%5B%7B%22name%22%3A%22Number+of+new+users%22%7D%2C%7B%7D%5D%2C%22series%22%3A%5B%7B%22type%22%3A%22bar%22%2C%22color%22%3A%22%23d7c1fa%22%2C%22label%22%3A%7B%22show%22%3Atrue%2C%22position%22%3A%22top%22%7D%2C%22encode%22%3A%7B%22xRef%22%3A%7B%22field%22%3A%22dbt_users_created_date_week%22%7D%2C%22yRef%22%3A%7B%22field%22%3A%22dbt_users_count_distinct_of_user_id%22%7D%7D%2C%22smooth%22%3Afalse%2C%22yAxisIndex%22%3A0%7D%5D%7D%7D%7D%2C%22tableConfig%22%3A%7B%22columnOrder%22%3A%5B%22dbt_users_created_date_week%22%2C%22dbt_users_count_distinct_of_user_id%22%5D%7D%2C%22organizationUuid%22%3A%22d413dcea-4c8f-46b6-baa5-23885490e08b%22%2C%22spaceUuid%22%3A%22c6bc2f47-32ba-4141-a8a6-80618abb18cc%22%2C%22spaceName%22%3A%22Shared%22%2C%22pinnedListUuid%22%3Anull%2C%22pinnedListOrder%22%3Anull%2C%22dashboardUuid%22%3Anull%2C%22dashboardName%22%3Anull%2C%22colorPalette%22%3A%5B%22%237262FF%22%2C%22%23D7C1FA%22%2C%22%2398F4D1%22%2C%22%23000000%22%2C%22%23fc8452%22%2C%22%23fac858%22%2C%22%23ff4d56%22%2C%22%233ba272%22%5D%2C%22slug%22%3A%22how-many-users-were-created-each-week-%22%2C%22isPrivate%22%3Afalse%2C%22access%22%3A%5B%7B%22userUuid%22%3A%2239b4685e-840b-48c8-b84b-b0f90b76d923%22%2C%22firstName%22%3A%22Katie%22%2C%22lastName%22%3A%22Hindson%22%2C%22email%22%3A%22katie%40lightdash.com%22%2C%22role%22%3A%22admin%22%2C%22hasDirectAccess%22%3Afalse%2C%22inheritedRole%22%3A%22admin%22%2C%22inheritedFrom%22%3A%22organization%22%2C%22projectRole%22%3A%22admin%22%7D%5D%7D)
