### ISSUE TITLE
Big Number charts in Scheduled Deliveries look a bit broken

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4921]
<img width="823" alt="Screenshot 2023-03-27 at 11 05 56" src="https://user-images.githubusercontent.com/12776522/227910521-4fc338d6-6433-4728-b8bb-1265d996cb4e.png">

The chart looks tiny

**Comment by rephus** [comment]
I thought we fixed this @IrakliJani ...

**Comment by IrakliJani** [comment]
should be fixed @PriPatel did this happen recently?

**Comment by PriPatel** [comment]
@IrakliJani I think it is still happening! The following email is from April 17th
<img width="1014" alt="Screenshot 2023-04-20 at 10 24 32" src="https://user-images.githubusercontent.com/12776522/233275505-dec0fa42-fe08-4d5d-9bc5-de2bd3454dd8.png">
