### ISSUE TITLE
Dashboard filters do not override chart filters if the filter operators are not the same

### ISSUE THREAD

**Issue by bhavna-shukla** [lightdash/lightdash#9965]
Uploading ovrride bug 0502.mp4…

### Description

Issue:
Seeing incorrect data on dashboard if operator used in Dashboard filter is different from operator in chart.

### Steps to Reproduce the Bug or Issue

Steps:
1. Create a test chart and save with a filter date = in the last 1 month
2. Add the chart to a dashboard
3. On the dashboard, add a filter for date = '2024-01-01' 

**Actual result:**
The dashboard filter would be added to the chart filter. So, the chart would be filtered on date = in the last 1 month AND date ='2024-01-01'
. The result is that the chart will still only show data from in the last 1 month
 
**Expected Result**

DB filter shall override chart filter, with different type of operators on same field.

### Cloud or self-hosting

None

**Comment by bhavna-shukla** [comment]
<img width="1346" alt="image" src="https://github.com/lightdash/lightdash/assets/167811334/157d75d1-fca2-430d-afd7-f3ed449b75cf">

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @bhavna-shukla 

This issue has been resolved here: #7268 so I'm going to close this issue

Can you please make sure you're on the latest version of Lightdash?

**Comment by bhavna-shukla** [comment]
Hi Katie https://github.com/lightdash/lightdash/issues/7268 this one only works if operators are same. It is still broken if operators are differnt

**Comment by TuringLovesDeathMetal** [comment]
Thanks for flagging that - I've reopened this issue

**Comment by TuringLovesDeathMetal** [comment]
Note: this was a requirement in this issue: https://github.com/lightdash/lightdash/issues/7268
